# Generated by Django 6.1.1 on 2026-09-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerpurchase",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerreview",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerpayment",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="customerpurchase",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="customerpurchaseitem",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="customerreview",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="customerpurchaseitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="customerreview",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="customerreviewitem",
            name="review",
        ),
        migrations.RemoveField(
            model_name="customerreviewitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="retailunit",
            name="mall",
        ),
        migrations.RemoveField(
            model_name="retailunit",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="CustomerPayment",
        ),
        migrations.DeleteModel(
            name="CustomerPurchase",
        ),
        migrations.DeleteModel(
            name="CustomerPurchaseItem",
        ),
        migrations.DeleteModel(
            name="CustomerReview",
        ),
        migrations.DeleteModel(
            name="CustomerReviewItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="RetailUnit",
        ),
        migrations.DeleteModel(
            name="Tenant",
        ),
    ]
